### ISSUE TITLE
Improve system notification

### ISSUE THREAD

**Issue by panno8M** [godot-nim/godot#10]
Show followings in editor output and stdout:

- [x] Show register result (X classes registered)
- [ ] Show use state (X classes used in current scene)

**Comment by panno8M** [comment]
related to #9

@insomniacUNDERSCORElemon Any other suggestions?

**Comment by insomniacUNDERSCORElemon** [comment]
> Any other suggestions?

Honestly I don't understand programming enough to know what's viable here. If classes *were* classifiable by scene (or perhaps scene *type*, such as menu, or even 2d vs 3d which would depend on which view you're in) I would say it'd be more useful to have that part of the info (instead of just all classes).
